name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            python3-pip openjdk-17-jdk unzip zip \
            git autoconf automake libtool pkg-config \
            zlib1g-dev libncurses5-dev libffi-dev libssl-dev \
            libsqlite3-dev libjpeg-dev libfreetype6-dev
          pip install --upgrade pip
          pip install Cython buildozer

      - name: Build APK
        run: |
          buildozer -v android debug || true
          ls -la bin/

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: kivy-apk
          path: bin/*.apk
