name: Build Kivy APK

on:
  push:
    branches:
      - main   # يشتغل كلما دفعت كود على الفرع main
  workflow_dispatch:  # يسمح لك تشغيله يدويًا من GitHub Actions

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip python3-setuptools python3-wheel git zip unzip openjdk-17-jdk
          pip install --upgrade pip
          pip install buildozer cython

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-kivy-app
          path: bin/*.apk
